import { createHmac, createHash, randomBytes } from "crypto";

const SERVER_SECRET = process.env.ANALYTICS_TOKEN_SECRET ?? "dev-secret-change-in-prod";

/** SHA-256 hash of input string (for IP+UA visitor fingerprinting). */
export async function sha256(input: string): Promise<string> {
  const encoder = new TextEncoder();
  const data = encoder.encode(input);
  const hash = await crypto.subtle.digest("SHA-256", data);
  return Array.from(new Uint8Array(hash))
    .map((b) => b.toString(16).padStart(2, "0"))
    .join("");
}

/**
 * Generate HMAC-SHA256 matching PostgreSQL's hmac() function.
 * PostgreSQL RPC uses: hmac(input, key, 'sha256')
 * We must produce the same output here for token verification.
 */
async function hmacSha256(input: string, key: string): Promise<string> {
  return new Promise((resolve, reject) => {
    const hmac = createHmac("sha256", key);
    hmac.update(input);
    const digest = hmac.digest();
    resolve(Array.from(new Uint8Array(digest))
      .map((b) => b.toString(16).padStart(2, "0"))
      .join(""));
  });
}

/**
 * Verify a tracking token generated by record_and_increment_share_view RPC.
 * Token format: hex_hmac|epoch_timestamp
 * PostgreSQL RPC: hmac(share_id|timestamp, server_secret, 'sha256')
 * Valid for 60 seconds after generation.
 */
export async function verifyTrackingToken(
  token: string,
  shareId: string,
): Promise<boolean> {
  try {
    const parts = token.split("|");
    if (parts.length !== 2) return false;

    const [hexHmac, epochStr] = parts;
    const epoch = Number(epochStr);
    if (isNaN(epoch)) return false;

    // Token must be less than 60 seconds old
    const nowEpoch = Math.floor(Date.now() / 1000);
    if (Math.abs(nowEpoch - epoch) > 60) return false;

    // Recompute HMAC matching PostgreSQL's hmac() output
    const message = `${shareId}|${epochStr}`;
    const expectedHmac = await hmacSha256(message, SERVER_SECRET);
    return hexHmac === expectedHmac;
  } catch {
    return false;
  }
}

/** Generate a signed tracking token for client-side ping (fallback if RPC token missing). */
export async function generateTrackingToken(
  shareId: string,
  rpcToken: string,
): Promise<string> {
  if (rpcToken && rpcToken.includes("|")) return rpcToken;

  const epoch = Math.floor(Date.now() / 1000);
  const hexHmac = await hmacSha256(`${shareId}|${epoch}`, SERVER_SECRET);
  return `${hexHmac}|${epoch}`;
}
